### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rguimaraesr** [StephenOTT/GitHub-Analytics#13]
When I try to run bundle install in the app dir, it shows:

[!] There was an error parsing `Gemfile`: 'GitHub-Analytics Web App' is not a valid gem name because it contains whitespace.. Bundler cannot continue.

 #  from /Users/rgr2k/GitHub-Analytics/app/Gemfile:4
 #  -------------------------------------------
 #  #Specify your gem's dependencies in sinatra_auth_github.gemspec
 >  gemspec
 #
 #  -------------------------------------------

**Comment by StephenOTT** [comment]
Will take a look. Think this was a carry over from older code changes. Been a while since I have used this app. Will fix it up this week for you. 

Any specific use case you are looking to report on?

**Comment by rguimaraesr** [comment]
Hey, not a specific case. I was just trying to install, read the steps. First I installed mongodb on my macbook, then, git clone the repository, then folder app and run mongd and in another terminal I run bundle install so I got this message. I think the install guide maybe wrong or lack of information in some points.

**Comment by rguimaraesr** [comment]
I`m looking forward to use this. It will help my QA work to get metrics about my github issues.

**Comment by StephenOTT** [comment]
Any specific metrics you trying to look at?






On Sat, Aug 1, 2015 at 12:09 PM -0700, "rguimaraesr" <notifications@github.com> wrote:












I`m looking forward to use this. It will help my QA work to get metrics about my github issues.

**Comment by rguimaraesr** [comment]
I use github issues as a bugtracker. So, I use labels to filter bugs that are open or closed. 

Metrics based on labels; 

Ex: An issue that has as **labels:** {BUG, type: API, type: GET} 

So I can **count** how many bugs has open to issues like that, then, I can get metrics, about, how often an bug ocurr in API with methods GET and so on...

Understand?

**Comment by rguimaraesr** [comment]
Hey, any update?

**Comment by StephenOTT** [comment]
Hey sorry have not looked at it yet.  Sorry been busy with work stuff.  Will look at is very shortly.  It is in my calendar.  If you don't hear some me by Sunday, please poke me again.  But should see a resolution before end of sunday.

**Comment by rguimaraesr** [comment]
ok @StephenOTT ! Thank you so much for attention :+1:

**Comment by rguimaraesr** [comment]
toc toc

**Comment by jegb** [comment]
replace 'GitHub-Analytics Web App' by 'GitHub-Analytics_Web_App' in sinatra_auth_github.gems

**Comment by StephenOTT** [comment]
Ahh Crap!! sorry guys... this fell through the cracks and I forgot about it...

**Comment by StephenOTT** [comment]
Okay this has been fixed as per @jegb.

@rguimaraesr you had caught me at the worst time, just as i was starting a new project... 

See master for updated gem spec.
https://github.com/StephenOTT/GitHub-Analytics/commit/7f464fa06da3d44da5f415a1d606b59d63b7a854
